### ISSUE TITLE
Migrate to ProjectPythia org for publishing

### ISSUE THREAD

**Issue by dcamron** [ProjectPythia/xbatcher-ML-1-cookbook#2]
Hi @cmdupuis3! I've invited you to be a member of the ProjectPythia organization, for which you should receive an email and notification. Once you accept this, please go to your repo Settings > Danger Zone > Transfer Ownership and Transfer it to the ProjectPythia organization (you'll still have full access to your repo.) Once you do so, then we can restart the machinery in ProjectPythia/cookbook-gallery#119 to publish this!

**Comment by cmdupuis3** [comment]
Done
